services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DATABASE_URL=postgres://postgres:password@db:5432/ru_connect_development

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ru_connect_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
